### ISSUE TITLE
Student access to material during semester

### ISSUE THREAD

**Issue by k8hertweck** [fredhutchio/tfcb_2020#2]
Last time, we didn't release content for each lecture or homework until the day of class, as it was maintained in separate branches while in development. This time, the material will be visible to the class at the beginning (if we leave the repo as it stands). 

If we are comfortable having all content visible for the the entire course, but continue to update, I recommend we include a note in the syllabus (README) and explain at the beginning of class that no one should expect the material be in its final form until a specified time prior to class, and to regularly update the repo to get current materials.

**Comment by rasi** [comment]
@k8hertweck I agree with having the content visible for the entire course.

**Comment by k8hertweck** [comment]
This has been noted below the schedule, and will be explained the first day of class.
